---
profile:
  title: Hello, I'm i-spin!
  name: i-spin
  image:
    path: /images/newpfp.png
    dimentions:
      height: 100%
      width: 100%
contacts: 
  discord: i-spin#9974
  twitter: sourTaste000
  github: i-spin
gallary:
  -
    title: Fight Another Day
    caption: 2021-01-23
    path: "/images/fight another day.jpeg"
  -
    title: Stratosphere
    caption: 2021-04-29
    path: "/images/stratosphere.jpeg"
  -
    title: Castle
    caption: 2021-06-30
    path: "/images/castle.jpeg"
  -
    title: Civilization
    caption: 2021-07-20
    path: "/images/civilization.jpeg"
  -
    title: Island
    caption: 2022-01-01
    path: "/images/island.jpeg"