---
profile:
  title: Hello, I'm i-spin!
  name: i-spin
  image:
    path: /images/newpfp.png
    dimentions:
      height: 50%
contacts: 
  discord: i-spin#9974
  twitter: sourTaste000
  github: i-spin
commissions:
  "Fight Another Day":
    image: /images/example.jpg