---
profile:
  title: I'm i-spin!
  name: i-spin
  about: |+
    Hello! Most people know me by my old name sourTaste000. I like programming, playing video games, listening to music and talking to people :D
    Currently, I am learning mostly front-end things like designing websites. This website is a good example!
    I built this website using [Next.js](https://nextjs.org/) and [Geist UI](https://geist-ui.dev/), and you can see the source code of this website [here](https://github.com/Discord-bot-monitor/profile-gen).
    I created this website to help artists quickly create websites with just one config file, including the basics such as a gallery and an information page.
    You can add more pages however, which is coming soon!
  image:
    path: /images/newpfp.png
    dimentions:
      height: 100%
      width: 100%
  contacts: 
    - 
      platform: Discord
      value: i-spin#9974
    -
      platform: Twitter
      value: sourTaste000
    -
      platform: GitHub
      value: i-spin
gallery:
  -
    title: Fight Another Day
    caption: 2021-01-23
    path: "/images/fight another day.jpeg"
  -
    title: Stratosphere
    caption: 2021-04-29
    path: "/images/stratosphere.jpeg"
  -
    title: Castle
    caption: 2021-06-30
    path: "/images/castle.jpeg"
  -
    title: Civilization
    caption: 2021-07-20
    path: "/images/civilization.jpeg"
  -
    title: Island
    caption: 2022-01-01
    path: "/images/island.jpeg"
pages:
  -
    name: Terms of Service
    path: '/extras/tos.md'
  -
    name: Test Page
    path: '/extras/test.md'